Repository maestrano/mno-enterprise-angular, pull requests merged in 2018-05, with the labels that each got.

#469 [MNOE-1055] [MNOE-1070] [OPAL-439] IE Public Pages Issues
  src/app/components/mno-apps/mno-app-listing.html
  src/app/components/mno-local-products/mno-local-product-listing.html
  src/app/stylesheets/variables.less
  src/app/views/public/public.less
Labels: bug

#442 [OPAL-353] Json schema conditional fields
  bower.json
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/details.html
  src/app/views/provisioning/details.less
  src/app/views/provisioning/subscription.controller.coffee
  src/app/views/provisioning/subscription.html
  src/locales/zh.json
Labels: enhancement

#460 [MNOE-974] App provisioning workflow
  src/app/components/mno-app-install-btn/mno-app-install-btn.coffee
  src/app/components/mnoe-api/provisioning.svc.coffee
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/order.controller.coffee
  src/app/views/provisioning/order.html
  src/app/views/provisioning/summary.html
  src/locales/en.json
Labels: enhancement

#467 [OPAL-305] Update Product pricings when organization is changed
  src/app/components/mno-apps/mno-app.coffee
Labels: bug

#484 [OPAL-420] Subscription Workflow
  src/app/components/mno-app-install-btn/mno-app-install-btn.coffee
  src/app/components/mno-local-products/mno-local-product.html
  src/app/components/mnoe-api/marketplace.svc.coffee
  src/app/components/mnoe-api/provisioning.svc.coffee
  src/app/index.route.coffee
  src/app/views/layout.controller.coffee
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/details.html
  src/app/views/provisioning/layout.html
  src/app/views/provisioning/order.controller.coffee
  src/app/views/provisioning/order.html
  src/app/views/provisioning/subscriptions.controller.coffee
  src/app/views/provisioning/subscriptions.html
  src/app/views/provisioning/summary.controller.coffee
  src/locales/en.json
Labels: enhancement

#480 [MNOE-1041] Capture Organization address on UI
  src/app/components/dashboard-company-selectbox/modals/create-company.controller.coffee
  src/app/components/dashboard-company-selectbox/modals/create-company.html
  src/app/components/mno-address-input/mno-address-input.coffee
  src/app/components/mno-address-input/mno-address-input.html
  src/app/components/mno-address-input/mno-address-input.less
  src/app/components/mnoe-api-old/miscellanous.coffee
  src/app/components/mnoe-api/organizations.svc.coffee
  src/app/index.default-config.coffee
  src/app/views/account/account.controller.coffee
  src/app/views/account/account.html
  src/app/views/company/credit-card/organization-credit-card.directive.coffee
  src/app/views/company/credit-card/organization-credit-card.html
  src/app/views/company/settings/organization-settings.directive.coffee
  src/app/views/company/settings/organization-settings.html
  src/app/views/company/settings/organization-settings.less
  src/locales/en.json
Labels: enhancement

#488 [MNOE-1113] Setup dashboard for cancelling subscriptions
  src/app/components/mno-local-products/mno-local-product.html
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/subscriptions.html
  src/app/views/provisioning/summary.controller.coffee
  src/app/views/provisioning/summary.html
  src/locales/en.json
Labels: bug

#482 [MNOE-1099] UX when no pricing plans in the billing currency
  src/app/components/mno-app-install-btn/mno-app-install-btn.coffee
  src/app/components/mno-app-install-btn/mno-app-install-btn.html
  src/app/components/mno-apps/mno-app.coffee
  src/app/components/mno-apps/mno-app.html
  src/locales/en.json
Labels: enhancement

#492 [OPAL-461] Pass productId to $stateParams from Local Product
  src/app/components/mno-local-products/mno-local-product.html
Labels: bug

#494 [MNOE-1117] Provisioning event sorting
  src/app/components/mnoe-api/provisioning.svc.coffee
  src/app/views/provisioning/subscription.controller.coffee
Labels: bug

#496 [MNOE-1133] Fix Product Pricing Flash
  src/app/views/provisioning/order.controller.coffee
Labels: bug

#485 [MNOE-1083] Company Cart System
  src/app/components/dashboard-company-cart/dashboard-company-cart.coffee
  src/app/components/dashboard-company-cart/dashboard-company-cart.html
  src/app/components/dashboard-company-cart/dashboard-company-cart.less
  src/app/components/dashboard-menu/dashboard-menu.html
  src/app/components/mnoe-api/provisioning.svc.coffee
  src/app/components/theme-editor/theme-editor.directive.coffee
  src/app/index.route.coffee
  src/app/stylesheets/variables.less
  src/app/views/layout.html
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/confirm.less
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/order.controller.coffee
  src/app/views/provisioning/subscription.controller.coffee
  src/app/views/provisioning/subscription.html
  src/app/views/provisioning/subscription.less
  src/app/views/provisioning/subscriptions.controller.coffee
  src/app/views/provisioning/subscriptions.html
  src/app/views/provisioning/summary.controller.coffee
  src/app/views/provisioning/summary.html
  src/locales/en.json
Labels: enhancement

#483 [MNOE-1036] Error occurs when adding member to team
  src/app/components/mnoe-api/teams.svc.coffee
  src/app/views/company/team-list/team-list.directive.coffee
Labels: Status: Review Needed, bug

#499 [MNOE-1160] Update Company Cart when organization is switched
  src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.coffee
  src/app/components/mnoe-api/provisioning.svc.coffee
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/subscriptions.controller.coffee
Labels: bug

#500 [MNOE-1137] Company Cart System: Issue with Modifying subscription within the cart
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/locales/en.json
Labels: bug
