Repository maestrano/mno-enterprise-angular, pull requests merged in 2018-03, with the labels that each got.

#436 [MNOE-884] Added flag checks for billing detials to not show in user management
  src/app/views/company/members/modals/edition-modal.html
  src/app/views/company/members/modals/invite-modal.html
  src/app/views/company/members/organization-members.directive.coffee
  src/locales/en.json
Labels: Status: Review Needed, enhancement

#437 [OPAL-290] Added a fix to prevent members from clicking on provisioning app
  src/app/components/mno-app-install-btn/mno-app-install-btn.html
Labels: bug

#441 [MNOE-956] Removed logos from billing details page
  src/app/views/company/credit-card/organization-credit-card.html
Labels: enhancement

#432 [MNOE-872] Session timeout modal
  src/app/components/mno-session-timeout/mno-session-timeout.html
  src/app/components/mno-session-timeout/mno-session-timeout.svc.coffee
  src/app/index.config.coffee
  src/app/index.default-config.coffee
  src/app/index.route.coffee
  src/locales/en.locale.json
Labels: Status: Review Needed, enhancement

#443 Fix indentation
  src/app/components/mno-session-timeout/mno-session-timeout.svc.coffee
Labels: bug

#444 [OPAL-421] Added check to prevent members from provisioning local products
  src/app/views/marketplace/marketplace-product.controller.coffee
Labels: bug
