Repository maestrano/mno-enterprise-angular, pull requests merged in 2018-07, with the labels that each got.

#487 [MNOE-1088] Quote Based Pricing
  src/app/components/mno-apps/mno-app.html
  src/app/components/mno-local-products/mno-local-product.coffee
  src/app/components/mno-local-products/mno-local-product.html
  src/app/components/mnoe-api/provisioning.svc.coffee
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/order.controller.coffee
  src/app/views/provisioning/summary.controller.coffee
  src/app/views/provisioning/summary.html
  src/locales/en.json
  src/locales/impac/en.json
  src/locales/impac/zh.json
Labels: enhancement

#523 [MNOE-1204] licenses n/a present on confirm page not on subscriptions page
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/subscription.html
  src/app/views/provisioning/subscriptions.html
  src/locales/en.json
Labels: bug

#527 [MNOE-1239] Removed status heading from app management page
  src/app/views/apps-management/apps-management.html
  src/locales/en.json
Labels: bug

#510 [MNOE-1159] Prevent member users from requesting cart subscriptions
  src/app/components/dashboard-company-cart/dashboard-company-cart.coffee
  src/app/components/dashboard-company-selectbox/dashboard-company-selectbox.coffee
  src/app/components/mnoe-api/provisioning.svc.coffee
  src/app/views/layout.controller.coffee
  src/app/views/layout.html
Labels: bug

#518 [MNOE-1149] add tooltips and improve bootstrap for subscription tables
  src/app/views/provisioning/order.html
  src/app/views/provisioning/subscriptions.html
Labels: bug

#519 [MNOE-1110][OPAL-431] Order details copying over
  src/app/components/mno-app-install-btn/mno-app-install-btn.coffee
  src/app/components/mno-local-products/mno-local-product.html
  src/app/components/mnoe-api/provisioning.svc.coffee
  src/app/index.route.coffee
  src/app/views/layout.controller.coffee
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/order.controller.coffee
  src/app/views/provisioning/order.html
  src/app/views/provisioning/subscriptions.controller.coffee
  src/app/views/provisioning/subscriptions.html
  src/app/views/provisioning/summary.controller.coffee
  src/locales/en.json
Labels: bug, enhancement

#531 [OPAL-513] Locales displayed on "Validate"
  src/app/components/mno-app-install-btn/mno-app-install-btn.coffee
  src/app/views/provisioning/summary.controller.coffee
Labels: bug

#530 [MNOE-1260]Add abandon to cancel subscription button
  src/app/views/provisioning/subscriptions.html
Labels: bug

#532 [MNOE-1263] [OPAL-497] Updated local products provision button
  src/app/components/mno-local-products/mno-local-product.coffee
  src/app/components/mno-local-products/mno-local-product.html
Labels: bug
