Repository maestrano/mno-enterprise-angular, pull requests merged in 2018-06, with the labels that each got.

#509 [MNOE-1164] order summary not showing
  src/app/views/provisioning/confirm.controller.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/summary.controller.coffee
  src/app/views/provisioning/summary.html
  src/locales/en.json
Labels: bug

#508 [OPAL-459] Fix Licenses not resetting bug
  src/app/views/provisioning/order.controller.coffee
Labels: bug

#512 [MNOE-1149] add tooltip on pricing plan selection table
  src/app/views/provisioning/order.html
Labels: enhancement

#511 [MNOE-1167] UI tooltip updated for item removal from cart and code cl…
  src/app/components/mnoe-api/provisioning.svc.coffee
  src/app/views/provisioning/subscriptions.controller.coffee
  src/app/views/provisioning/subscriptions.html
  src/locales/en.json
Labels: bug

#514 [MNOE-1172] Fixed multiple bugs in subscription actions flow
  src/app/index.route.coffee
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/summary.controller.coffee
  src/app/views/provisioning/summary.html
  src/locales/en.json
Labels: bug

#498 [MNOE-1140] Can provision app from admin panel but not marketplace
  src/app/components/mno-app-install-btn/mno-app-install-btn.coffee
  src/app/components/mno-apps/mno-app.coffee
  src/app/components/mno-apps/mno-app.html
  src/app/components/mnoe-config/mnoe-config.svc.coffee
  src/app/services/provisioning-helper/provisioning-helper.coffee
  src/app/views/apps-management/app-management/app-management.controller.coffee
  src/app/views/provisioning/order.controller.coffee
Labels: Status: Review Needed, bug

#497 [MNOE-1139] AppManagement: Subscriptions Events should show in Order History Tab
  src/app/components/mnoe-api/provisioning.svc.coffee
  src/app/views/apps-management/app-management/app-management.controller.coffee
  src/app/views/apps-management/app-management/app-management.html
  src/locales/en.json
Labels: bug

#513 [MNOE-1166] Max licenses UI improvements
  src/app/services/provisioning-helper/provisioning-helper.coffee
  src/app/views/provisioning/confirm.html
  src/app/views/provisioning/order.html
  src/app/views/provisioning/summary.html
  src/locales/en.json
Labels: bug

#520 [MNOE-1148] Fixed issues with provisioning of products for members
  src/app/components/mno-app-install-btn/mno-app-install-btn.coffee
  src/app/components/mno-local-products/mno-local-product.coffee
  src/app/components/mno-local-products/mno-local-product.html
Labels: bug

#517 [MNOE-1183] Sync status not showing on App Management page
  src/app/components/mnoe-api/app-instances.svc.coffee
  src/app/services/app-management-helper/app-management-helper.coffee
  src/app/views/apps-management/app-management/app-management.controller.coffee
  src/app/views/apps-management/app-management/app-management.html
  src/app/views/apps-management/apps-management.controller.coffee
  src/app/views/apps-management/apps-management.html
Labels: bug

#521 [MNOE-1186] Refresh the subscriptions screen when changing company
  src/app/components/mno-local-products/mno-local-product-listing.coffee
  src/app/views/provisioning/subscriptions.controller.coffee
Labels: bug

#524 [MNOE-1218][MNOE-1219] Fix contract length typo and order page currency default
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/order.controller.coffee
Labels: bug

#525 [MNOE-1220][MNOE-1221] Product bugs
  src/app/components/mno-apps/mno-app.coffee
  src/app/components/mno-apps/mno-app.html
  src/app/services/app-management-helper/app-management-helper.coffee
  src/app/services/provisioning-helper/provisioning-helper.coffee
Labels: bug

#450 [MNOE-1007] Improve Marketplace Filtering
  src/app/components/mno-apps/mno-app-listing.coffee
  src/app/components/mno-apps/mno-app-listing.html
Labels: enhancement

#522 [MNOE-1171] Add loader when loading custom schema
  src/app/views/provisioning/details.controller.coffee
  src/app/views/provisioning/order.controller.coffee
  src/locales/en.json
Labels: bug

#526 [MNOE-1203] Product Markups
  src/app/components/mnoe-api/marketplace.svc.coffee
Labels: bug
