Repository maestrano/mno-enterprise-angular, pull requests merged in 2018-09, with the labels that each got.

#540 [MNOE-1277] Product display allow undefined org
  src/app/components/mno-apps/mno-app.coffee
Labels: Status: In Testing, bug

#543 [OPALSUP-281] Add billing currency flag
  src/app/components/mnoe-config/mnoe-config.svc.coffee
  src/app/views/company/settings/organization-settings.directive.coffee
  src/app/views/company/settings/organization-settings.html
  src/app/views/company/settings/organization-settings.less
  src/locales/en.json
Labels: enhancement

#536 [OPALSUP-286] Existing Active end user should not be allowed to be invited again
  src/app/views/company/members/modals/invite-modal.html
  src/app/views/company/members/organization-members.directive.coffee
  src/app/views/company/members/organization-members.html
  src/locales/en.json
Labels: bug
